package k8s

import (
	"fmt"

	"k8s.io/apimachinery/pkg/api/meta"
	"k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/yaml"
)

// formatYAML serializes a Kubernetes runtime.Object to YAML, stripping
// the noise that hides what users actually care about:
//
//   - managedFields: a wall of server-side apply provenance, often longer
//     than the spec itself. kubectl now includes it by default and most
//     users hate it.
//   - kubectl.kubernetes.io/last-applied-configuration annotation: a
//     duplicate of half the spec, generated by old kubectl apply.
//
// Everything else (resourceVersion, uid, creationTimestamp) stays —
// useful debug context.
func formatYAML(obj runtime.Object) (string, error) {
	if accessor, err := meta.Accessor(obj); err == nil {
		accessor.SetManagedFields(nil)

		annotations := accessor.GetAnnotations()
		if annotations != nil {
			delete(annotations, "kubectl.kubernetes.io/last-applied-configuration")
			if len(annotations) == 0 {
				accessor.SetAnnotations(nil)
			} else {
				accessor.SetAnnotations(annotations)
			}
		}
	}

	out, err := yaml.Marshal(obj)
	if err != nil {
		return "", fmt.Errorf("marshal yaml: %w", err)
	}
	return string(out), nil
}
