// schemaForm/allOfMerger.ts — pure function that merges JSON Schema
// `allOf` composition into a flat schema the walker can render.
//
// Why this exists: K8s OpenAPI v3 represents inherited / embedded
// types via `allOf`. Every K8s resource's `metadata` field is
// `allOf: [{$ref: ObjectMeta}]`. CRDs generated by `kubebuilder`
// from Go types with embedded `metav1.ObjectMeta` produce the same
// shape. Without merging, the walker emits an `unsupported`
// descriptor for these fields and the operator sees the dreaded
// "yaml only" badge for `metadata` on every form-mode edit.
//
// Merge semantics:
//
//   - properties:        union of all entries' property maps. Later
//                        entries override earlier on key collision
//                        (matches JSON Merge Patch precedence).
//   - required:          union of all entries' required arrays
//                        (deduplicated).
//   - description:       last non-empty wins (lets the parent's own
//                        description override an inherited one from
//                        the base).
//   - default:           last non-undefined wins (same rationale).
//   - enum:              if multiple entries set enum, intersect them
//                        (the value must satisfy ALL — that's what
//                        allOf means). Empty intersection → drop the
//                        enum constraint to avoid silent breakage.
//   - type:              if all entries agree, that's the type.
//                        If they disagree, the merge fails (return
//                        original schema unchanged so the walker
//                        surfaces the failure as `unsupported`).
//   - everything else:   from the parent schema (the one that
//                        contained the `allOf`); allOf entries
//                        only contribute to the merged shape's
//                        properties / required / type / etc.
//
// We DO NOT merge `oneOf` from allOf entries — if any allOf entry
// has its own oneOf, leave the merged schema with that oneOf intact
// for the walker's discriminator detection to handle separately.
//
// We DO NOT recursively merge nested allOf inside allOf entries —
// derefIfNeeded handles `$ref` resolution before we see the entry,
// and the walker calls mergeAllOf on each derefed result, so nested
// allOfs flatten layer by layer naturally.

import type { JSONSchema } from "./types";

export interface MergeContext {
  /** Resolves $ref strings to their target schemas. Same shape as
   *  the WalkOptions.resolveRef the walker already uses. */
  resolveRef?: (ref: string) => JSONSchema | undefined;
  /** Set of refs we've already walked into during this merge,
   *  prevents infinite loops on recursive types. The walker's
   *  derefIfNeeded carries one too — same idea. */
  seen: Set<string>;
}

/** Merge `schema.allOf` into `schema` and return the merged result.
 *  When the schema has no `allOf`, returns the input unchanged.
 *  When the merge fails (incompatible types across entries),
 *  returns the input unchanged so the walker can surface the
 *  failure via its `unsupported` descriptor. */
export function mergeAllOf(schema: JSONSchema, ctx: MergeContext): JSONSchema {
  if (!schema || typeof schema !== "object") return schema;
  const allOf = schema.allOf;
  if (!Array.isArray(allOf) || allOf.length === 0) return schema;

  // Resolve each allOf entry (deref'ing $ref) and validate it's an
  // object we can read. Any unresolvable ref / non-object entry
  // aborts the merge — better to fall back to unsupported than
  // produce a partial merged shape.
  const resolved: JSONSchema[] = [];
  for (const entry of allOf) {
    const r = resolveEntry(entry, ctx);
    if (!r) return schema; // abort — surface as unsupported via walker
    resolved.push(r);
  }

  // Start from the parent's own properties (sans allOf) so non-merged
  // metadata like `description` / `pattern` / inline `properties`
  // carry through.
  const merged: JSONSchema = { ...schema };
  delete merged.allOf;

  // Merge properties — union, later entries override.
  const props: Record<string, JSONSchema> = { ...(schema.properties ?? {}) };
  for (const entry of resolved) {
    if (entry.properties) {
      for (const [k, v] of Object.entries(entry.properties)) {
        props[k] = v; // later wins
      }
    }
  }
  if (Object.keys(props).length > 0) merged.properties = props;

  // Merge required — union (dedupe).
  const requiredSet = new Set<string>(schema.required ?? []);
  for (const entry of resolved) {
    for (const r of entry.required ?? []) requiredSet.add(r);
  }
  if (requiredSet.size > 0) merged.required = Array.from(requiredSet);

  // Merge type — must agree, or merge fails.
  const types = new Set<string>();
  if (schema.type) addType(types, schema.type);
  for (const entry of resolved) {
    if (entry.type) addType(types, entry.type);
  }
  if (types.size > 1) return schema; // conflict — surface as unsupported
  if (types.size === 1) merged.type = Array.from(types)[0];

  // Merge description / default — last non-empty wins.
  for (const entry of resolved) {
    if (typeof entry.description === "string" && entry.description) {
      merged.description = entry.description;
    }
    if (entry.default !== undefined) {
      merged.default = entry.default;
    }
  }

  // Merge enum — intersection. Drop the enum constraint if the
  // intersection is empty (operator can still type any value).
  const enums = [
    ...(schema.enum ? [schema.enum] : []),
    ...resolved.filter((e) => e.enum).map((e) => e.enum as unknown[]),
  ];
  if (enums.length > 0) {
    let intersection = enums[0];
    for (let i = 1; i < enums.length; i++) {
      intersection = intersection.filter((v) => enums[i].includes(v));
    }
    if (intersection.length > 0) {
      merged.enum = intersection;
    } else {
      delete merged.enum;
    }
  }

  // Preserve oneOf from any entry — let the walker's discriminator
  // detection handle it separately. Multiple entries with their own
  // oneOf would be ambiguous; we take the first one that has it.
  if (!merged.oneOf) {
    for (const entry of resolved) {
      if (Array.isArray(entry.oneOf)) {
        merged.oneOf = entry.oneOf;
        break;
      }
    }
  }

  // Preserve additionalProperties from any entry that defines it
  // (last wins, like properties). Only relevant for merged objects.
  for (const entry of resolved) {
    if (entry.additionalProperties !== undefined) {
      merged.additionalProperties = entry.additionalProperties;
    }
  }

  return merged;
}

function resolveEntry(
  entry: JSONSchema,
  ctx: MergeContext,
): JSONSchema | undefined {
  if (!entry || typeof entry !== "object") return undefined;
  if (entry.$ref === undefined) return entry;
  if (!ctx.resolveRef) return undefined;
  const ref = entry.$ref;
  if (ctx.seen.has(ref)) return undefined; // cycle
  const resolved = ctx.resolveRef(ref);
  if (!resolved) return undefined;
  ctx.seen.add(ref);
  // If the resolved schema is itself a $ref or has its own allOf,
  // recurse — the merger flattens nested allOf layer by layer.
  if (resolved.$ref) return resolveEntry(resolved, ctx);
  if (Array.isArray(resolved.allOf)) {
    return mergeAllOf(resolved, ctx);
  }
  return resolved;
}

function addType(set: Set<string>, t: string | string[]): void {
  if (typeof t === "string") {
    set.add(t);
    return;
  }
  if (Array.isArray(t)) {
    for (const x of t) {
      if (typeof x === "string" && x !== "null") set.add(x);
    }
  }
}
