apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "periscope.fullname" . }}-auth
  labels:
    {{- include "periscope.labels" . | nindent 4 }}
data:
  auth.yaml: |
    {{- toYaml .Values.auth | nindent 4 }}
