apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "periscope.fullname" . }}-clusters
  labels:
    {{- include "periscope.labels" . | nindent 4 }}
data:
  clusters.yaml: |
    clusters:
      {{- toYaml .Values.clusters | nindent 6 }}
