apiVersion: v1
kind: Service
metadata:
  name: {{ include "periscope.fullname" . }}
  labels:
    {{- include "periscope.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
{{- if .Values.agent.enabled }}
    - name: tunnel
      port: {{ trimPrefix ":" .Values.agent.listenAddr | atoi | default 8443 }}
      targetPort: tunnel
      protocol: TCP
{{- end }}
  selector:
    {{- include "periscope.selectorLabels" . | nindent 4 }}
